# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.synced_folder "chef-repo/", "/root/chef-zero", create: true, group: "root", owner: "root"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.define :test_server do |host|
    host.vm.box = "ubuntu-14.04"
    host.vm.hostname = "test-server"

    host.vm.box_url = 'https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box'
    host.vm.network :private_network, ip: "192.168.33.12"
    host.vm.provision :shell, :path => 'init.sh'
  end

 end
